
version: "3.5"

services:
  databaseGui0:
    image: dockage/phppgadmin
    depends_on:
      - "database"
    environment:
      - PHP_PG_ADMIN_MIN_PASSWORD_LENGTH=0
      - PHP_PG_ADMIN_SERVER_HOST=database
      - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=unbabel
    ports:
      - 7000:80
      
  databaseGui1:
    image: dpage/pgadmin4
    depends_on:
      - "database"
    environment:
      - PGADMIN_DEFAULT_EMAIL=brunoais@localhost
      - PGADMIN_DEFAULT_PASSWORD=testingpassword
      - PGADMIN_LISTEN_PORT=7001
    ports:
      - 7001:7001
    volumes:
      - ./containers/pgadmin:/var/lib/pgadmin

  database:
    image: postgres
    shm_size: 256MB
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=testingpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./containers/postgresql/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
